// Склеивает PNG-секвенции рейнджера в горизонтальные спрайтлисты + JSON-метадату.
// Источник: assets/Forest_Ranger_<n>/PNG/PNG Sequences/<Animation>/*.png (900×900).
// Цель:     public/ranger/<n>/<slug>.png (FRAME_SIZE × N кадров) + <slug>.json.
//
// Запуск: `node scripts/build-sprites.mjs` (или `npm run build-sprites`).
// Идемпотентен: перезатирает существующие.

import { promises as fs } from "node:fs";
import path from "node:path";
import sharp from "sharp";

const ROOT = path.resolve(import.meta.dirname, "..");
const SRC_DIR = path.join(ROOT, "assets");
const OUT_DIR = path.join(ROOT, "public", "ranger");

// Финальный размер одного кадра. 256 хватает для отображения ~200px высоты;
// дальше CSS-масштабом не теряем чёткость. Сжимает 18-кадровый Idle с
// ~1.5MB → ~250KB одним PNG-листом.
const FRAME_SIZE = 256;

// Какие анимации экспортируем и под каким url-slug'ом. Имя slug идёт в
// компонент <Ranger animation="..." /> — стабильный API, не зависит от
// исходного имени папки.
const ANIMATIONS = [
  { src: "Idle", slug: "idle" },
  { src: "Idle Blinking", slug: "idle-blinking" },
  { src: "Jump Start", slug: "jump-start" },
  { src: "Jump Loop", slug: "jump-loop" },
  { src: "Running", slug: "running" },
  { src: "Hurt", slug: "hurt" },
  { src: "Dying", slug: "dying" },
];

const VARIANTS = [1, 2, 3];

async function buildOne(variant, anim) {
  const srcDir = path.join(
    SRC_DIR,
    `Forest_Ranger_${variant}`,
    "PNG",
    "PNG Sequences",
    anim.src,
  );

  let entries;
  try {
    entries = await fs.readdir(srcDir);
  } catch {
    return { variant, slug: anim.slug, status: "skip (no source folder)" };
  }
  const frames = entries
    .filter((f) => f.toLowerCase().endsWith(".png"))
    .sort(); // сортировка по имени = по индексу кадра (0_..._000, 001, 002...)
  if (frames.length === 0) {
    return { variant, slug: anim.slug, status: "skip (empty)" };
  }

  // Resize каждый кадр до FRAME_SIZE×FRAME_SIZE с прозрачным фоном —
  // contain, чтобы пропорции не поплыли.
  const resized = await Promise.all(
    frames.map((f) =>
      sharp(path.join(srcDir, f))
        .resize(FRAME_SIZE, FRAME_SIZE, {
          fit: "contain",
          background: { r: 0, g: 0, b: 0, alpha: 0 },
        })
        .png()
        .toBuffer(),
    ),
  );

  // Склейка горизонтально через composite.
  const sheetWidth = FRAME_SIZE * frames.length;
  const sheet = sharp({
    create: {
      width: sheetWidth,
      height: FRAME_SIZE,
      channels: 4,
      background: { r: 0, g: 0, b: 0, alpha: 0 },
    },
  })
    .composite(
      resized.map((input, i) => ({ input, left: i * FRAME_SIZE, top: 0 })),
    )
    .png({ compressionLevel: 9, palette: true });

  const outDir = path.join(OUT_DIR, String(variant));
  await fs.mkdir(outDir, { recursive: true });
  const pngPath = path.join(outDir, `${anim.slug}.png`);
  await sheet.toFile(pngPath);
  // Метаданные о числе кадров пишем в TS-манифест (см. buildManifest ниже) —
  // компонент <Ranger> читает их через import, без runtime-fetch'а JSON.

  const bytes = (await fs.stat(pngPath)).size;
  return {
    variant,
    slug: anim.slug,
    frames: frames.length,
    status: `ok ${frames.length} кадров, ${(bytes / 1024).toFixed(0)} KB`,
  };
}

async function buildManifest(results) {
  // Финальный TS-манифест: { [variant]: { [slug]: { frames, frameWidth, frameHeight } } }.
  // Импортируется компонентом <Ranger>, чтобы знать число кадров без fetch.
  const manifest = {};
  for (const r of results) {
    if (!r.success) continue;
    manifest[r.variant] ??= {};
    manifest[r.variant][r.slug] = {
      frames: r.frames,
      frameWidth: FRAME_SIZE,
      frameHeight: FRAME_SIZE,
    };
  }
  const tsPath = path.join(ROOT, "src", "components", "ranger-frames.ts");
  const content =
    "// AUTO-GENERATED by scripts/build-sprites.mjs — не править вручную.\n" +
    "// Манифест спрайтлистов рейнджера: число кадров на анимацию.\n\n" +
    "export type RangerVariant = 1 | 2 | 3;\n" +
    "export type RangerAnimation =\n" +
    [...new Set(results.filter((r) => r.success).map((r) => `\"${r.slug}\"`))]
      .map((s) => `  | ${s}`)
      .join("\n") +
    ";\n\n" +
    "export type SpriteMeta = { frames: number; frameWidth: number; frameHeight: number };\n\n" +
    "export const RANGER_SPRITES: Record<RangerVariant, Record<RangerAnimation, SpriteMeta>> = " +
    JSON.stringify(manifest, null, 2) +
    ";\n";
  await fs.writeFile(tsPath, content);
  console.log(`\n📝 манифест: ${path.relative(ROOT, tsPath)}`);
}

async function main() {
  const tasks = [];
  for (const v of VARIANTS) {
    for (const a of ANIMATIONS) {
      tasks.push(
        buildOne(v, a).then((r) => ({
          ...r,
          success: r.status.startsWith("ok"),
        })),
      );
    }
  }
  const results = await Promise.all(tasks);
  for (const r of results) {
    console.log(`Ranger ${r.variant}/${r.slug}: ${r.status}`);
  }
  await buildManifest(results);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
